- rpmrepo.py
Gzip stores modification time in compressed files.
Since we don't provide mtime in gzip_string, gunzip_string it uses
current time.
XML files filelists and primary are gzipped twice, so if they are
generated at different times, they'll be different. And their checksums
will be different.
This commit removes the 2nd compression of files.
> Fix filelists, primary checksum inconsistency.

- rpmrepo.py
<rpm:vendor> content can contain xml symbols (like < or > if some uri is specified).
Closes #10
> Fix XML parsing error

- debrepo.py
Since the latest ubuntu/bionic the new default pack
format for debian packages is in use by dpkg tool:
tar.gz -> tar.xz
also Tarantool core packages uses versioning names like:
tarantool_2.3.0.62.g6c627af39-1_amd64.deb
but not as expected:
tarantool_2.3.0-62.g6c627af39-1_amd64.deb
Closes #14
> Implement xz packing and new versioning

- README.md
- debrepo.py
- rpmrepo.py
The PR includes several fixes for signature and adds the ability to specify the gpg secret key for signing by using the env variable.
> Add the ability to specify the secrete key

- rpmrepo.py
Before the patch, processing of the "repomd.xml" file will fail because there is no "revision" field.
> Fix processing of the "revision" field

- README.md
- debrepo.py
Added the ability to specify the values of several fields ("Source", "Label" and "Description") for the "Release" file through environment variables.
Closes #22
> deb: add the ability to specify "Origin", "Label" and "Description"

- README.md
- debrepo.py
- mkrepo.py
- rpmrepo.py
Now, when adding packages to the index, if an malformed package is present, the program will be terminated. In some cases, the desired program behavior is to correctly create an index with all correct packages and display a message about the presence of
malformed ones.
This behavior can now be set using the "--force" option.
> Add force mode

- debrepo.py
Before the patch, the following expression was used when processing the "Architectures" and "Components" fields from the release file:
`architectures = release['Architectures'].split(' ')`
But in the case of `release['Architectures'] == ''` `architectures` will be `['']` and the following `for` will not work correctly (it will iterate for an empty `arch`). Now in the case of `release['Architectures'] == ''` `architectures` will be `[]` and `for` would not iterate over a such list.
> Fix processing several fields from a Release file

- rpmrepo.py
- test/dummy_storage.py
- test/test_other.py
- test/test_rpmrepo.py
Mkrepo didn't generate other.xml.gz, which is needed for adding,
for example, CentOs 7. Additional methods were added to a script
rpmrepo.py, so that it would generate other.xml.gz file, as there
was only two files filelists and primary .xml.gz with metainformation
previously.
repodata/other.xml.gz, with the description this file currently
only stores the changelog data from packages.
http://blog.sweetxml.org/2008/03/anatomy-of-yum-repository-look-under.html
https://en.opensuse.org/openSUSE:Standards_Rpm_Metadata#How_to_extend_rpm-md_metadata_with_non_standard_data
Was added several unittests to check dump_other and
header_to_other functions.
Close knazarov/mkrepo#32
I think it depends now on the #41. 
I tried creating the other file with the next diff
```
@@ -961,12 +961,20 @@ def …
```
> Add generation of other.xml.gz file

- debrepo.py
Before this patch in PackageIndex the default arch is always use.
By a lucky coincidence, this did not break anything, but it may cause a bug in the future.
> deb: fix specifying of arch in PackageIndex

- rpmrepo.py
- test/test_other.py
Before the patch, the architecture of the package was written in
metadata for srpm, but this is not correct. For srpm, the
archetecture field must be filled with "src".
Tip:
To view the value of some tag in the rpm header use:
`rpm --query --package package.src.rpm --queryformat "%{TAG_NAME}\n"`
Related to tarantool/tarantool-qa#148
> Fix architecture definition for srpm

- test/test_other.py
This typo causes the "flake8" check to fail: "E231 missing whitespace after ':'".
Let's fix it.
> Fix a typo

- setup.py
For PIP project it is possible to show a detailed description of the
package. This is shown on the package detail page on the Python Package
Index [1]. Patch allows showing a long description loaded from
README.md, which is a common pattern [2].
1. https://pypi.org/project/mkrepo/
2. https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata
> Add a long description to PIP package page

- debrepo.py
- test/resources/source.dsc
- test/test_debrepo.py
Sometimes *.dsc files can be signed and mkrepo didn't handle such cases.
Now it is fixed. Also, added a test for parsing a signed *.dsc file.
Part of #58
> Fix parsing signed dsc files

- rpmrepo.py
- setup.py
- test/test_rpmrepo.py
This patch fixes the issue occurred while syncing live/1.10/el/7/x86_64
tarantool repo:
2022-06-01T15:43:52.167754425Z app[web.1]: Traceback (most recent call last):
2022-06-01T15:43:52.167954314Z app[web.1]:   File "/app/.heroku/python/bin/mkrepo", line 5, in <module>
2022-06-01T15:43:52.167969891Z app[web.1]:     mkrepo.main()
2022-06-01T15:43:52.167979377Z app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/mkrepo.py", line 117, in main
2022-06-01T15:43:52.168122234Z app[web.1]:     update_repo(path, args)
2022-06-01T15:43:52.168157987Z app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/mkrepo.py", line 59, in update_repo
2022-06-01T15:43:52.168168105Z app[web.1]:     rpmrepo.update_repo(stor, args.sign, args.temp_dir, args.force) …
> rpm: fix sync of live/1.10/el/7/x86_64 repo 

- rpmrepo.py
- setup.py
This patch fixes the issue 
```
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```
occurred while syncing one of our local rpm repositories. There's a case when every **item[1:]** list value is **NoneType**
following up on #63
> Fix2 dump primary func

- rpmrepo.py
The license XML tag may contain an ampersand character that should be
escaped, otherwise, it leads to the following error:
xml.etree.ElementTree.ParseError: not well-formed (invalid token)
As a result, it renders repository unusable. This patch fixes the issue
by escaping the `fmt['license']` value in the `dump_primary` function.
Example:
<rpm:license>OpenSSL & Chromium CLA</rpm:license>      <-- before
<rpm:license>OpenSSL &amp; Chromium CLA</rpm:license>  <-- after
> rpm: xml.etree.ElementTree.ParseError: not well-formed (invalid token)

- rpmrepo.py
- test/test_rpmrepo.py
This patch makes special XML characters be escaped in the `provides`,
`requires`, and `obsoletes` sections to avoid the following error:
xml.etree.ElementTree.ParseError: not well-formed (invalid token)
Note, commit c8ca21f7 (rpm: fix xml.etree.ElementTree.ParseError issue)
fixed the same issue but for the `license` section only.
Follows up #66
> rpm: escape special characters in XML

- rpmfile.py
- rpmrepo.py
SUMMARY, DESCRITPTION and GROUP header entry values were None. The fields are [RPM_I18NSTRING_TYPE](https://github.com/rpm-software-management/rpm/blob/master/lib/header.c#L41) types (type == 9). 
```
tag, type, offset, count
(1004, 9, 23, 1)
(1005, 9, 50, 1)
```
```
SUMMARY: None
DESCRIPTION: None
GROUP: None
```
> rpm: process i18nstring header types

- rpmfile.py
- rpmrepo.py
1. Adding “primary” files into primary.xml. The [rpm-software-management/createrepo_c](https://github.com/rpm-software-management/createrepo_c/blob/d8da644c45bec1429d600c619ce4e47af5906ef8/src/misc.h#L110) source code. 
Doing it the right way using FILEMODES rpm header field. With FILEMODES, we can distinguish files (symlinks, regular files) from directories.
2. Converting flags to string exactly as [rpm-software-management/createrepo_c](https://github.com/rpm-software-management/createrepo_c/blob/d8da644c45bec1429d600c619ce4e47af5906ef8/src/misc.c#L51) does, RPMSENSE_SENSEMASK bit mask is set to [15](https://github.com/rpm-software-management/rpm/blob/bf1771b/include/rpm/rpmds.h#L61).
3. Fix rpmrepo.py when it is going to be run as a separate script (convenient for debugging on
local …
> rpm: fix primary.xml

- rpmrepo.py
- test/test_rpmrepo.py
1. Add \<rpm:conflicts\> to primary.xml
2. [Skip primary package and provided files](https://github.com/rpm-software-management/createrepo_c/blob/master/src/parsehdr.c#L366) in \<rpm:requires\>
> rpm: fix primary xml - part 2

- .github/workflows/unittests.yml
- .gitignore
Eliminate the following warning:
Node.js 12 actions are deprecated. For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2
> ci: bump checkout and setup-python action versions

- CHANGELOG.md
- rpmrepo.py
Fix Python 3.6 compatibility by replacing the `removesuffix()` method, which 
is available since Python 3.9.0, with another code.
> rpm: python36 compatibility

- CHANGELOG.md
- rpmrepo.py
- test/test_rpmrepo.py
> rpm: escape url in primary.xml
